### ISSUE TITLE
Get rid of the light bulb device

### ISSUE THREAD

**Issue by bogdanbun** [DeutscheMark/homebridge-kodi#13]
Is there a way to get rid of the light bulb device? I would like to keep only the "TV" device and control it using the iOS13 remote control, but so far whatever I do the light bulb is still there.

**Comment by DeutscheMark** [comment]
Yes, of course that's possible to add.
It's due to the first version of the app where the light bulb was the standard accessory and some optional accessories could be added. Now with the addition of the TV accessories and other optional ones I'll consider making the light bulb optional in one of the next versions as well. Thanks for pointing that out.

**Comment by DeutscheMark** [comment]
`player` > `main` added in v0.3.2.
