### ISSUE TITLE
Feature request: Kodi WakeUp

### ISSUE THREAD

**Issue by i3laze** [DeutscheMark/homebridge-kodi#6]
I recently added a Siri shortcut to Pause playback (HomeKit action: turn on Pause) — it’s voice activated and kinda useful.

My request is to add some switch to wake Kodi from screensaver (which eventually turns on my TV via HDMI-CEC). 
While some movie is paused, hitting Pause or Play switch powers on TV.. but when nothing is played, hitting switches gives no effect. 

Actually it might be a switch to turn Kodi ScreenSaver off and on. 
(My current screensaver is “Turn off LG TV ” https://forum.kodi.tv/showthread.php?tid=245169&pid=2880314)

**Comment by DeutscheMark** [comment]
I think this feature could come in handy, but the API does not seem to have a command to deactivate a screensaver, it only supports notifications for when they are de/activated.

In order to achieve this you could send a custom command (like Select, Up or Back) to Kodi and Kodi would wake up automatically and also the TV would turn on with your screensaver.

This feature for custom commands and command chains is already in planning and will be released with one of the coming versions, maybe with 0.4.0.

Thanks, keep the good ideas coming, they help me a lot. :)

**Comment by i3laze** [comment]
Indeed, it might be useful to pass generic Kodi Functions as a string variable for momentary switch accessory or as part of Controls accessory, like keymap actions on a regular remote:
https://kodi.wiki/view/List_of_built-in_functions

Be advised that will duplicate current “scan/clean library” switches.

**Comment by DeutscheMark** [comment]
Hi, with the new command sequences in v0.4.0 you should now easily achieve your goal.
Maybe try it with the *home* command? It should wake up Kodi and your TV via HDMI-CEC.
